In [1]:
import imp
import sys
import os
import pandas as pd
import numpy as np
import math
from math import factorial
import logging

import warnings
warnings.filterwarnings("ignore")

sys.path.append(os.path.abspath(os.path.join("../scripts")))
import preprocess
import data_loader

/tmp/ipykernel_5764/2363800194.py:1: DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses
  import imp

In [2]:
logging.basicConfig(filename='./logfile.log', filemode='a',
                    encoding='utf-8', level=logging.DEBUG)

In [3]:
df = data_loader.load_data('../data/AdSmartABdata.csv')
df

,auction_id,experiment,date,hour,device_make,platform_os,browser,yes,no
0,0008ef63-77a7-448b-bd1e-075f42c55e39,exposed,2020-07-10,8,Generic Smartphone,6,Chrome Mobile,0,0
1,000eabc5-17ce-4137-8efe-44734d914446,exposed,2020-07-07,10,Generic Smartphone,6,Chrome Mobile,0,0
2,0016d14a-ae18-4a02-a204-6ba53b52f2ed,exposed,2020-07-05,2,E5823,6,Chrome Mobile WebView,0,1
3,00187412-2932-4542-a8ef-3633901c98d9,control,2020-07-03,15,Samsung SM-A705FN,6,Facebook,0,0
4,001a7785-d3fe-4e11-a344-c8735acacc2c,control,2020-07-03,15,Generic Smartphone,6,Chrome Mobile,0,0
...,...,...,...,...,...,...,...,...,...
8072,ffea24ec-cec1-43fb-b1d1-8f93828c2be2,exposed,2020-07-05,7,Generic Smartphone,6,Chrome Mobile,0,0
8073,ffea3210-2c3e-426f-a77d-0aa72e73b20f,control,2020-07-03,15,Generic Smartphone,6,Chrome Mobile,0,0
8074,ffeaa0f1-1d72-4ba9-afb4-314b3b00a7c7,control,2020-07-04,9,Generic Smartphone,6,Chrome Mobile,0,0
8075,ffeeed62-3f7c-4a6e-8ba7-95d303d40969,exposed,2020-07-05,15,Samsung SM-A515F,6,Samsung Internet,0,0
8076,fffbb9ff-568a-41a5-a0c3-6866592f80d8,control,2020-07-10,14,Samsung SM-G960F,6,Facebook,0,0

In [14]:
### Remove 
# excluding who did not respond
df_clean = preprocess.nonResponse(df)

In [15]:
df_clean

,auction_id,experiment,date,hour,device_make,platform_os,browser,yes,no
16,008aafdf-deef-4482-8fec-d98e3da054da,exposed,2020-07-04,16,Generic Smartphone,6,Chrome Mobile,1,0
23,00b6fadb-10bd-49e3-a778-290da82f7a8d,control,2020-07-08,4,Samsung SM-A202F,6,Facebook,1,0
45,018af862-486e-4da1-a85b-71872120e57c,control,2020-07-03,15,Generic Smartphone,6,Chrome Mobile,1,0
65,023ec7b5-cb8f-49a5-995f-e0d7c2f702e5,exposed,2020-07-09,13,Samsung SM-G935F,6,Facebook,1,0
89,02efdb70-8596-4f3f-b0b2-b91e194f61f7,exposed,2020-07-05,6,Generic Smartphone,6,Chrome Mobile,1,0
...,...,...,...,...,...,...,...,...,...
8016,fd86fc6b-3420-4f81-9df0-98fa1f15abf5,exposed,2020-07-08,17,Samsung SM-G965F,6,Facebook,0,1
8058,ff95df43-63b4-48c8-8497-781ba7952eec,exposed,2020-07-09,18,Generic Smartphone,6,Chrome Mobile,0,1
8064,ffb79718-6f25-4896-b6b3-e58b80a6e147,control,2020-07-09,7,Generic Smartphone,6,Chrome Mobile,0,1
8069,ffca1153-c182-4f32-9e90-2a6008417497,control,2020-07-10,16,Generic Smartphone,6,Chrome Mobile,0,1
8071,ffdfdc09-48c7-4bfb-80f8-ec1eb633602b,exposed,2020-07-03,4,Generic Smartphone,6,Chrome Mobile,0,1

In [16]:
df_clean['browser'].value_counts()

Chrome Mobile                 695
Chrome Mobile WebView         227
Facebook                      156
Samsung Internet              145
Mobile Safari                  14
Mobile Safari UI/WKWebView      3
Chrome                          2
Chrome Mobile iOS               1
Name: browser, dtype: int64

In [17]:
df_clean['platform_os'].value_counts()

6    1226
5      17
Name: platform_os, dtype: int64

Data to retain for the modeling are Chrome Mobile, Chrome Mobile WebView, Facebook, Samsung Internet puis platform 6.

### Version in dvc
- Chrome Mobile: v4
- Chrome Mobile WebView: v6
- Facebook: v7
- Samsung Internet: 10
- platform 6: v3

In [18]:
df_clean.head()

,auction_id,experiment,date,hour,device_make,platform_os,browser,yes,no
16,008aafdf-deef-4482-8fec-d98e3da054da,exposed,2020-07-04,16,Generic Smartphone,6,Chrome Mobile,1,0
23,00b6fadb-10bd-49e3-a778-290da82f7a8d,control,2020-07-08,4,Samsung SM-A202F,6,Facebook,1,0
45,018af862-486e-4da1-a85b-71872120e57c,control,2020-07-03,15,Generic Smartphone,6,Chrome Mobile,1,0
65,023ec7b5-cb8f-49a5-995f-e0d7c2f702e5,exposed,2020-07-09,13,Samsung SM-G935F,6,Facebook,1,0
89,02efdb70-8596-4f3f-b0b2-b91e194f61f7,exposed,2020-07-05,6,Generic Smartphone,6,Chrome Mobile,1,0

### Processing
- Remove auctionid
- encode experiment (hot encoding)
- remove date
- encode device (label encoder)
- encode browser (label encoder)
- target is yes, remove no

In [19]:
torem = ['auction_id', 'date', 'no']
df_clean = preprocess.remove(df_clean, torem)

In [20]:
df_clean.head()

   experiment  hour         device_make  platform_os        browser  yes
16    exposed    16  Generic Smartphone            6  Chrome Mobile    1
23    control     4    Samsung SM-A202F            6       Facebook    1
45    control    15  Generic Smartphone            6  Chrome Mobile    1
65    exposed    13    Samsung SM-G935F            6       Facebook    1
89    exposed     6  Generic Smartphone            6  Chrome Mobile    1

In [21]:
df_clean = preprocess.hot_encode(df_clean,'platform_os')

In [22]:
df_clean['browser'], dic_browser = preprocess.encode(df_clean, 'browser')
df_clean['device_make'], dic_device = preprocess.encode(df_clean, 'device_make')
df_clean['experiment'], dic_experiment = preprocess.encode(df_clean, 'experiment')

In [23]:
df_clean

      experiment  hour  device_make  platform_os  browser  yes  platform_os 6
16             1    16           13            6        1    1              1
23             0     4           43            6        4    1              1
45             0    15           13            6        1    1              1
65             1    13           65            6        4    1              1
89             1     6           13            6        1    1              1
...          ...   ...          ...          ...      ...  ...            ...
8016           1    17           69            6        4    0              1
8058           1    18           13            6        1    0              1
8064           0     7           13            6        1    0              1
8069           0    16           13            6        1    0              1
8071           1     4           13            6        1    0              1

[1243 rows x 7 columns]

In [2]:
import pandas as pd

In [6]:
pd.read_csv('../data/data_Chrome Mobile WebView.csv')

,auction_id,experiment,date,hour,device_make,platform_os,browser,yes,no
0,03ee1780-1fa3-4bec-926c-d543a81a6653,exposed,2020-07-04,11,Samsung SM-G981B,6,Chrome Mobile WebView,1,0
1,046644f4-b30c-48f9-b069-f804a97b77d9,exposed,2020-07-05,2,Generic Smartphone,6,Chrome Mobile WebView,1,0
2,07567ef2-71de-41c4-b234-79565a48917e,exposed,2020-07-08,20,Generic Smartphone,6,Chrome Mobile WebView,1,0
3,0ae26cd6-a8c9-4fe3-b561-4a405d4bf0e4,control,2020-07-03,15,Samsung SM-A202F,6,Chrome Mobile WebView,1,0
4,0af12f96-1167-4717-85c2-e4bab19a6741,exposed,2020-07-08,21,Samsung SM-A405FN,6,Chrome Mobile WebView,1,0
...,...,...,...,...,...,...,...,...,...
222,ecf7f3e3-198a-46a2-9916-e5c4af543f51,exposed,2020-07-03,13,Generic Smartphone,6,Chrome Mobile WebView,0,1
223,f0a15526-6329-41e2-a867-5ac06eb3a1e8,exposed,2020-07-09,8,Pixel 2,6,Chrome Mobile WebView,0,1
224,f63133b5-7748-4423-bca9-6e5b409a53e6,exposed,2020-07-08,14,Generic Smartphone,6,Chrome Mobile WebView,0,1
225,fa4f3a29-0b51-4fb2-b1e8-8e1bc0ae8373,exposed,2020-07-10,8,Samsung SM-A300FU,6,Chrome Mobile WebView,0,1
226,fc3f29c6-5204-4cf2-b418-608ff0ab1282,control,2020-07-10,12,Samsung SM-A520F,6,Chrome Mobile WebView,0,1